name: CD pipline
on:
  workflow_run:
  workflows: ["CI pipline"]
  types:
    - completed
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull the image for docker hub
      - run: sudo docker pull nirobahammad89/test-project-ci-cd:latest
      - name: Remove old docker conatiner
      - run: sudo rm -f test-project-ci-cd-container || true
      - name: Install the new Docker image
      - run: sudo docker run -d -p 3000:3000 --name test-project-ci-cd-container nirobahammad89/test-project-ci-cd
