name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        with:
          DU: ${{secrets.DOCKER_USERNAME}}
          DP: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DU -p $DP

      - name: Build Docker Image
        run: docker build -t $DU/test-project-ci-cd:latest .

      - name: Push the image to Docker Hub
        run: docker push $DU/test-project-ci-cd:latest
