name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        run: docker login -u nirobahammad89 -p Milon@34279582

      - name: Build Docker Image
        run: docker build -t test-project-ci-cd .

      - name: Push the image to Docker Hub
        run: docker push nirobahammad89/test-project-ci-cd
