name: CI Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install --update

      - name: Login to ECR Docker
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 831181103474.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build the Docker image
        run: docker build -t test-ecr .

      - name: Tag the Docker image
        run: docker tag test-ecr:latest 831181103474.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest

      - name: Push the Docker image to ECR
        run: docker push 831181103474.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest
