name: CI Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install

      - name: Login to ECR Docker
        run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 831181103474.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build the Docker image
        run: docker build -t test-ecr .

      - name: Tag the Docker image
        run: docker tag test-ecr:latest 831181103474.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest

      - name: Push the Docker image to ECR
        run: docker push 831181103474.dkr.ecr.ap-south-1.amazonaws.com/test-ecr:latest
