name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    -name: Login Docker
    env:
    DU: ${{test.DU}}
    DP: ${{test.DU}}
      run: docker login -u $DU -p $DP

    name: Build Docker Image
      run: docker build -t test-project-ci-cd .

    name: Push the image in docker hub
    run: docker push $DU/test-project-ci-cd:latest
