name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        env:
          DU: ${{ secrets.DOCKER_USERNAME }} # Correct reference to GitHub secret
          DP: ${{ secrets.DOCKER_PASSWORD }} # Correct reference to GitHub secret
        run: docker login -u $DU -p $DP

      - name: Build Docker Image
        run: docker build -t test-project-ci-cd .

      - name: Push the image to Docker Hub
        run: docker push $DU/test-project-ci-cd:latest
