name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        env:
          DU: ${{ secrets.DOCKER_USERNAME }}
          DP: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DP | docker login -u $DU --password-stdin

      - name: Build Docker Image
        run: docker build -t test-project-ci-cd .

      - name: Push the image to Docker Hub
        run: docker push $DU/test-project-ci-cd:latest
